CREATE TABLE comments
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    content VARCHAR(255),
    post_id BIGINT      NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
