export const MAJORS = [
  'Accounting',
  'Architecture',
  'Biology',
  'Business Administration',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Computer Engineering',
  'Computer Science',
  'Economics',
  'Electrical Engineering',
  'Environmental Science',
  'Finance',
  'Industrial Engineering',
  'Information Systems',
  'International Relations',
  'Law',
  'Management',
  'Marketing',
  'Mathematics',
  'Mechanical Engineering',
  'Medicine',
  'Physics',
  'Political Science',
  'Psychology',
  'Sociology',
  'Software Engineering',
  'Statistics',
]
