server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/student_forum_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=admin1234

# ElasticSearch
spring.elasticsearch.uris=http://localhost:9200