spring.application.name=backend
spring.profiles.active=dev
spring.config.import=optional:file:.env[.properties]

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.cookie.secure=${JWT_COOKIE_SECURE}

