server.port=8080

# Database
spring.datasource.url=jdbc:h2:file:./data/mydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# ElasticSearch
spring.elasticsearch.uris=http://localhost:9200

# Swagger
springdoc.api-docs.path=/sw-api/api-docs
springdoc.swagger-ui.path=/swagger-ui