spring.application.name=backend
spring.profiles.active=dev
spring.config.import=optional:file:.env[.properties]

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Swagger
springdoc.api-docs.path=/sw-api/api-docs
springdoc.swagger-ui.path=/swagger-ui

