spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/student_forum
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

security.jwt.secret.key=ZjNiY2UxYTk1Yjc2MmQxZjhlNDA3YTZkMGY0ZmNiYWJjYTNmNDVlNzgyMGE4YzNiMDFjMjdmOWY0YzZkOGU5Yg==
security.jwt.expiration.time=3600000
